theme: jekyll-theme-cayman
title: Thomas Beucher
description: Welcome to my website, you will find some of my work here.
titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true 
